job.name=cheating-detection-job
task.class=CheatingDetectionTask

systems.kafka.samza.factory=org.apache.samza.system.kafka.KafkaSystemFactory
systems.kafka.consumer.zookeeper.connect=localhost:2181
systems.kafka.producer.bootstrap.servers=localhost:9092

task.inputs=kafka.student-activity,kafka.webcam-events